### PR TITLE
Update todo-java-postgresql-terraform README

### PR DESCRIPTION
**Pull request by v-xuto**
Update todo-java-postgresql-terraform README to use `azd init` and `azd up` instead of `azd up --template` according to https://github.com/Azure/azure-dev/issues/1769.

@jongio, @rajeshkamal5050, @fangjian0423  for notification.

### CODE REVIEW

**Comment by fangjian0423** [comment]
@v-xuto This template will move to https://github.com/Azure-Samples/todo-java-postgresql-terraform, refer https://github.com/Azure/azure-dev/pull/1792.

When the PR merged, will archive this repository and handle `todo-java-postgresql-aca-terraform` template.

**Comment by v-xuto** [comment]
@fangjian0423 Thanks for the reminder, I have created a new PR https://github.com/Azure-Samples/todo-java-postgresql-terraform/pull/1, please review. If there are no problems, I will close the current PR https://github.com/fangjian0423/todo-java-postgresql-terraform/pull/4.

**Comment by rajeshkamal5050** [comment]
@v-xuto @fangjian0423 Can we close this one? since we have a new one - https://github.com/Azure-Samples/todo-java-postgresql-terraform

**Comment by v-xuto** [comment]
@rajeshkamal5050 Okay. I will close it.

**Pull request closed without merging**
